apiVersion: batch/v1
kind: Job
metadata:
  name: job-app-ml
spec:
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: kyrylprojector/app-ml:latest
          name: job-app-ml
          