---
apiVersion: v1
kind: Pod
metadata:
  name: load-fastapi-naive
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - 'locust -f /app/load-testing/locustfile.py --host=http://app-fastapi.default.svc.cluster.local:8080 --users 100 --spawn-rate 20 --autostart --run-time 600s'
    image: kyrylprojector/app-fastapi-week-6:latest
    imagePullPolicy: Always
    name: load
    ports:
    - containerPort: 8089
      protocol: TCP
---
