apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: custom-model
spec:
  predictor:
    minReplicas: 1
    containers:
      - name: kserve-container
        image: kyrylprojector/kserve-custom:latest

  transformer:
    minReplicas: 1
    containers:
      - image: kyrylprojector/kserve-custom-transformer:latest
        name: kserve-container
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-custom
spec:
  consumerGroup: knative-group-custom
  # Broker URL. Replace this with the URLs for your kafka cluster,
  # which is in the format of my-cluster-kafka-bootstrap.my-kafka-namespace:9092.
  bootstrapServers:
    - kafka-headless.default.svc.cluster.local:9092
  topics:
    - custom
  sink:
    ref:
      apiVersion: serving.kserve.io/v1beta1
      kind: InferenceService
      name: custom-model
    uri: /v1/models/custom-model:predict

