---
apiVersion: v1
kind: Pod
metadata:
  name: load-fastapi-naive
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - 'locust -f load-testing/locustfile.py --host=http://app-fastapi.default.svc.cluster.local:8080 --users 50 --spawn-rate 10 --autostart --run-time 600s'
    image: 823217009914.dkr.ecr.us-west-2.amazonaws.com/riva-tts-fast-api:latest
    imagePullPolicy: Always
    name: l2
    ports:
    - containerPort: 8089
      protocol: TCP
---
