apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: ab-test
  namespace: default
spec:
  name: ab-test
  namespace: default
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: kyrylprojector/app-seldon-monitoring:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'          
          - name: WANDB_API_KEY
            value: 228f8278fb1a0a60618d3e7b2461c1ced7ca6f8d             
          imagePullPolicy: Always
    
    graph:
      children: []
      endpoint:
        type: REST
      parameters:
      - name: model_id
        type: STRING
        value: truskovskiyk/nlp-sample/kfp-pipeline:latest

    name: default
    replicas: 1

  - componentSpecs:
    - spec:
        - image: kyrylprojector/app-seldon-monitoring:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'          
          - name: WANDB_API_KEY
            value: 228f8278fb1a0a60618d3e7b2461c1ced7ca6f8d             
          imagePullPolicy: Always
    graph:
      children: []
      endpoint:
        type: REST
      parameters:
      - name: model_id
        type: STRING
        value: truskovskiyk/nlp-sample/good-model:latest

    name: shadow
    replicas: 1
    shadow: true