apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-auto-scaling-sample
  namespace: default
spec:
  annotations:
    seldon.io/rest-timeout: "6000"
    seldon.io/grpc-timeout: "6000"
  protocol: seldon
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: kyrylprojector/app-seldon-monitoring:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'          
          - name: WANDB_API_KEY
            value: ********
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '5'
              memory: "2Gi"
            limits:
              cpu: '5'  
              memory: "2Gi"           
        terminationGracePeriodSeconds: 1000          
      hpaSpec:
        maxReplicas: 5  
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 1
          type: Resource
        minReplicas: 1
    graph:
      name: classifier
      type: MODEL
      parameters: [
        {
          "name": "model_id",
          "type": "STRING",
          "value": "truskovskiyk/nlp-sample/good-model:v0"
        }
      ]
    name: model
    replicas: 1
