apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-aim-deployment
  name: my-aim-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: my-aim-deployment
  template:
    metadata:
      labels:
        app: my-aim-deployment
    spec:
      containers:
        - image: kyrylprojector/aim:latest
          name: my-aim-deployment
          ports:
            - containerPort: 43800
              protocol: TCP
          volumeMounts:
            - mountPath: /aim
              name: aim-runs
      volumes:
        - name: aim-runs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-aim-service
spec:
  selector:
    app: my-aim-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 43800