{
 "title": "statistical-metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Real Time Model Accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(true_pos{method=\"feedback\"} + true_neg{method=\"feedback\"}) by (seldon_app)) / (sum(true_pos{method=\"feedback\"} + true_neg{method=\"feedback\"} + false_pos{method=\"feedback\"} + false_neg{method=\"feedback\"}) by (seldon_app))",
     "legendFormat": "{{seldon_app}}"
    }
   ]
  },
  {
   "title": "Real Time Model Precision",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(true_pos{method=\"feedback\"}) by (seldon_app)) / (sum(true_pos{method=\"feedback\"} + false_pos{method=\"feedback\"}) by (seldon_app))",
     "legendFormat": "{{seldon_app}}"
    }
   ]
  },
  {
   "title": "Real Time Model Recall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(true_pos{method=\"feedback\"}) by (seldon_app)) / (sum(true_pos{method=\"feedback\"} + false_neg{method=\"feedback\"}) by (seldon_app))",
     "legendFormat": "{{seldon_app}}"
    }
   ]
  },
  {
   "title": "Real Time Model Specificity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(true_neg{method=\"feedback\"}) by (seldon_app)) / (sum(true_neg{method=\"feedback\"} + false_pos{method=\"feedback\"}) by (seldon_app))",
     "legendFormat": "{{seldon_app}}"
    }
   ]
  }
 ]
}