name: week-1-ci

on:
  push:
    branches:
      - 'main'
      - 'week-1'
env:
  IMAGE_ML_APP: app-ml
  IMAGE_ML_WEB: app-web


jobs:
  build-and-push-app-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: kyrylprojector
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: week-1/app-ml/
          file: week-1/app-ml/Dockerfile
          push: true
          tags: kyrylprojector/app-ml:dev
          cache-from: type=registry,ref=kyrylprojector/app-ml:buildcache
          cache-to: type=registry,ref=kyrylprojector/app-ml:buildcache,mode=max


  # build-and-push-app-web:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: week-1/app-web/
  #         file: week-1/app-web/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_ML_WEB }}:latest    
  #         cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_ML_WEB }}:buildcache
  #         cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_ML_WEB }}:buildcache,mode=max

  # # kind:
  # #   runs-on: ubuntu-latest
  # #   steps:
  # #     - uses: actions/checkout@master

  # #     - uses: engineerd/setup-kind@v0.5.0
    
  # #     - name: Testing
  # #       run: |
  # #         kubectl cluster-info
  # #         kubectl get pods -n kube-system
  # #         echo "current-context:" $(kubectl config current-context)
  # #         echo "environment-kubeconfig:" ${KUBECONFIG}

  # #     - name: Run job
  # #       run: |
  # #         kubectl create -f week-1/k8s-resources/job-app-ml.yaml
  # #         kubectl get pods
  # #         kubectl describe job job-app-ml
  # #         sleep 120
  # #         kubectl get pods
  # #         kubectl describe job job-app-ml
  # #         sleep 120
  # #         # kubectl wait --for=condition=complete --timeout=300s job/job-app-ml
  # #         kubectl get pods
  # #         kubectl describe pod

  # #     - name: Remove job
  # #       run: |
  # #         kubectl delete job/job-app-ml

  # minikube:

    runs-on: ubuntu-latest
    name: build example and deploy to minikube

    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - name: Try the cluster !
      run: kubectl get pods -A
    
    - name: Deploy job to minikube
      run: |
        kubectl create -f week-1/k8s-resources/job-app-ml.yaml 
        kubectl wait --for=condition=complete --timeout=300s job/job-app-ml
        kubectl get pod

    - name: Deploy app to minikube
      run: |
        # kubectl create -f week-1/k8s-resources/deployment-app-web.yaml
        kubectl get pod 
  
    # - name: Test service URLs
    #   run: |
    #     minikube service list
    #     minikube service deployments-app-web --url
    #     echo "------------------opening the service------------------"
    #     curl $(minikube service deployments-app-web --url)  