name: week-1-ci

on:
  push:
    branches:
      - '**'
      # - 'week-1'
env:
  IMAGE_ML_APP: app-ml
  IMAGE_ML_WEB: app-web


jobs:
  build-and-push-app-ml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login 
        run: |
          docker login -u kyrylprojector -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build 
        run: |
          docker build --tag kyrylprojector/app-web:latest ./week-1/app-web

      - name: Push 
        run: |
          docker push kyrylprojector/app-web:latest
          